#!/usr/bin/env bash
# Regenerate the Cloudflare real-IP snippet and reload nginx.
#
# Needed ONLY when the DNS records are proxied (orange cloud). Behind the
# proxy every request arrives from a Cloudflare edge address, so
# $remote_addr is Cloudflare — not the visitor. Left unset, the API's
# rate limiting buckets the entire internet into a handful of edge IPs:
# one busy user trips the limit for everyone, and a real attacker never
# does. These directives restore the visitor's address from
# CF-Connecting-IP.
#
# Cloudflare adds ranges over time. Run this from cron monthly:
#   0 4 1 * * /opt/minto/deploy/scripts/update-cloudflare-ips.sh
set -euo pipefail

OUT=/etc/nginx/snippets/minto-cloudflare-realip.conf
TMP=$(mktemp)

{
    echo "# Generated by update-cloudflare-ips.sh — do not edit by hand."
    echo "# Source: https://www.cloudflare.com/ips-v4 and /ips-v6"
    echo
    for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
        curl -fsS "$url" | while read -r cidr; do
            [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
        done
    done
    echo
    echo "real_ip_header CF-Connecting-IP;"
    # Without this a forged CF-Connecting-IP from a non-Cloudflare source
    # would be trusted; with it, only the ranges above may set it.
    echo "real_ip_recursive on;"
} > "$TMP"

# A truncated download would silently disable rate limiting; refuse it.
if [ "$(grep -c set_real_ip_from "$TMP")" -lt 10 ]; then
    echo "Refusing to install: only $(grep -c set_real_ip_from "$TMP") ranges fetched." >&2
    rm -f "$TMP"
    exit 1
fi

sudo install -m 644 "$TMP" "$OUT"
rm -f "$TMP"
sudo nginx -t && sudo systemctl reload nginx
echo "Installed $OUT"
