/**
 * True when `value` looks like one of our ids.
 *
 * Replaces the 244 scattered `mongoose.Types.ObjectId.isValid()` calls. Ids stay
 * 24-char hex after the Postgres move — the format is generated by pgcrypto and
 * asserted by the frontend (useActiveOrderTracking.js), so it is a real contract
 * and not just a leftover of Mongo.
 */
export const isId = (value) => /^[a-f0-9]{24}$/i.test(String(value ?? ''));

export const buildPaginationOptions = (query) => {
    const page = Math.max(parseInt(query.page, 10) || 1, 1);
    const limit = Math.min(Math.max(parseInt(query.limit, 10) || 20, 1), 100);
    const skip = (page - 1) * limit;

    return { page, limit, skip };
};

export const buildPaginatedResult = ({ docs, total, page, limit }) => {
    const totalPages = Math.ceil(total / limit) || 1;

    return {
        data: docs,
        meta: {
            total,
            page,
            limit,
            totalPages
        }
    };
};

